version: '3.8'

services:
  backend:
    image: munchies-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - "5000:5000"
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgres://munchies:munchies_password@postgres:5432/munchies_database
      - REDIS_URL=redis://redis:6379/1

  frontend:
    image: munchies-frontend
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - backend

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: munchies_database
      POSTGRES_USER: munchies
      POSTGRES_PASSWORD: Biosphere#1
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
